name: Push CSS to Project Wallace

on:
  push:
    branches: [main]

jobs:
  pushCss:
    name: Push CSS to projectwallace.com
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push CSS to Project Wallace
        run: |
          cat _includes/*.css > all.css
          curl https://www.projectwallace.com/api/webhooks/v2/imports?token=${{ secrets.PROJECT_WALLACE_TOKEN }} --request POST --header 'Content-Type: text/plain' --data @all.css"
